<form action="">
  <div class="form-group">
    <label for="">Placa</label>
    <input name="plate" type="text" class="form-control form-control-sm">
    <div class="invalid-feedback" id="plate-feedback">
    </div>
  </div>
  <div class="form-group">
    <label for="">Modelo</label>
    <input name="model" type="text" class="form-control form-control-sm">
    <div class="invalid-feedback" id="model-feedback">
    </div>
  </div>
  <div class="form-group">
    <label for="">Marca</label>
    <select name="make_id" id="" class="form-control form-control-sm">
    </select>
    <div class="invalid-feedback" id="make_id-feedback">
    </div>
  </div>
  <div class="form-group">
    <label for="">Tipo</label>
    <select name="class_id" id="" class="form-control form-control-sm">
    </select>
    <div class="invalid-feedback" id="class_id-feedback">
    </div>
  </div>
  <div class="form-group">
    <label for="">Ano</label>
    <input name="year_of" type="text" class="form-control form-control-sm">
    <div class="invalid-feedback" id="year_of-feedback">
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Salvar</button>
  <p id="message" class="mt-3"></p>
</form>
<?= $this->inlineScript()
  ->prependFile($this->basePath('js/services.js'))
?>
<script>
  $(document).ready(function() {
    services
      .allClasses()
      .then(classes => {
        const $class = $('select[name="class_id"]');
        classes.forEach(classCar => {
          $class.append('<option value="' + classCar.id + '">' + classCar.name + '</option>')
        });
      });
    services
      .allMakes()
      .then(makes => {
        const $class = $('select[name="make_id"]');
        makes.forEach(make => {
          $class.append('<option value="' + make.id + '">' + make.name + '</option>')
        });
      });
    $('form').submit(sendForm);
  });

  function sendForm(event) {
    event.preventDefault();
    $('input').removeClass('is-invalid');
    $('button').addClass('disabled').text('Salvando..');
    const $form = $(this);
    const input = $form.serialize();
    const $message = $('#message');
    $message.text('').removeClass('text-success text-danger');
    services
      .addCar(input)
      .then(() => {
        $('input').val('');
        $message
          .text('Carro salvo com sucesso!')
          .addClass('text-success');
        $('button').removeClass('disabled').text('Salvar');
      })
      .catch((error) => {
        const errors = error.responseJSON.errors;
        for (const key in errors) {
          let message = '';
          for( const keyMessage in errors[key] ) {
            if (keyMessage == 'isEmpty') {
              message += 'O Campo está vazio. ';
            } else {
              message += errors[key][keyMessage] + ' ';
            }
          }
          $('input[name="' + key + '"]').addClass('is-invalid');
          $('#'+ key +'-feedback')
            .text(message);
            
        }
        $message
          .text('Ocorreu um erro!')
          .addClass('text-danger');
        $('button').removeClass('disabled').text('Salvar');
      });
  }
</script>